ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= centos74-octave-fludetector

This Ansible playbook provisions a CentOS 7.4 machine with a single-node instance of the FluDetector app (https://github.com/UCL/fludetector-flask)

== Requirements

- Ansible (version 2.4.2) - https://www.ansible.com/
- Octave 4.x for CentOS - rpm archives available
- FluDetector model artifacts (version 2018.04) - tarball archive available by request

=== Octave

The playbook installs Octave from the rpm file. Make sure the file `octave-4.2.2-6.el7.centos.1.x86_64.rpm` is present in the playbook directory:

== Installation

Save the FluDetector model tarball archive in this directory, edit `hosts.ini` inventory file to set the hostname of the productive system 
and execute the ansible playbook to install the FluDetector app.

....
ansible-playbook -i hosts.ini --limit 'productive' -u [remoteuser] -b -k -K playbook.yml
....

== Testing

A Vagrant (https://www.vagrantup.com/) file is provided for local testing. It requires a CentOS 7.4 box installed with the name 'centos-7.4'. Fire up the vagrant up to test the installation:

....
vagrant up
....

The web interface is available on http://localhost:10080/

== Configuration of FluDetector model

=== Initial configuration

A script is provided to configure the application

....
cd /opt/fludetector
./scripts/init.sh
....

=== Install model data in SQLite instance

An SQL script with all the parameters required to run the model is provided in the tarball archive.
....
cd /opt/fludetector
tar xfO /tmp/FluDetectorModel-Google201804.tar.gz --wildcards '*.sql' | sudo sqlite3 data.db
....

=== Calculate model scores 

Install the Google API key in the `.env` file and run a model score calculation for dates in the past.
....
cd /opt/fludetector
sudo sed -i 's/^\(GOOGLE_API_KEY=\).*/\1APIKEY/' .env
sudo ./scripts/run.sh runmodel 1 --start [yyyy-mm-dd] --end [yyyy-mm-dd]
....

=== Start scheduler for calculation of model scores

Once the calculation of scores for past dates is completed, start the scheduler to run these calculations automatically on a daily basis.
....
sudo systemctl start supervisord
....