---
- hosts: '{{ target }}'
  become: True
  become_method: sudo
  vars:
    activemq_version: '5.15.3'
    glassfish_version: '5.0'
  tasks:
  - name: Create system user for ActiveMQ
    user:
      name: "{{item}}"
      system: yes
      local: yes
      createhome: yes
      home: "/opt/{{item}}"
      shell: /bin/nologin
    with_items:
      - activemq
      - glassfish

  - name: Install OpenJDK 8
    yum:
      name: 'java-1.8.0-openjdk'
      state: present

  - name: Download and unpack ActiveMQ
    unarchive:
      src: 'http://www.apache.org/dyn/closer.cgi?filename=/activemq/{{activemq_version}}/apache-activemq-{{activemq_version}}-bin.tar.gz&action=download'
      dest: /opt/activemq
      creates: '/opt/activemq/activemq-all-{{activemq_version}}.jar'
      remote_src: yes
      extra_opts: "--strip-components=1"
      owner: activemq
      group: activemq

  - name: Upload Systemd unit file for ActiveMQ
    copy:
      src: activemq.service
      dest: /usr/lib/systemd/system/activemq.service
        
  - name: Install unzip
    yum:
      name: unzip
      state: present

  - name: Download and unpack Glassfish
    unarchive:
      src: 'http://download.oracle.com/glassfish/{{glassfish_version}}/release/glassfish-{{glassfish_version}}.zip'
      dest: /opt
      creates: /opt/glassfish5
      remote_src: yes
      owner: glassfish
      group: glassfish

  - name: Move Glassfish files to HOME
    shell: mv /opt/glassfish5/* /opt/glassfish
    become_user: glassfish

  - name: Remove glassfish5 directory
    file:
      path: /opt/glassfish5
      state: absent

  - name: Upload Systemd unit file for Glassfish
    copy:
      src: glassfish.service
      dest: /usr/lib/systemd/system/glassfish.service

  - name: Start ActiveMQ and Glassfish
    service:
      name: "{{item}}"
      state: started
      enabled: yes
    with_items:
      - activemq
      - glassfish

  - name: Set JMS service type to LOCAL

  - name: Enable JMS Bridge Service (edit glassfish/domains/domain1/imq/instances/imqbroker/props/config.properties)

  - name: Restart Glassfish

  - name: Start STOMP Bridge (listens on localhost:7672)

  - name: Configure firewall
    command: 'firewall-cmd --zone=public --permanent --add-port={{item}}/tcp'
    with_items:
      - 8161
      - 61616
      - 61613

  - name: Reload firewall rules
    command: firewall-cmd --reload
