---
- hosts: '{{ target }}'
  become: True
  become_method: sudo
  vars:
    activemq_version: '5.15.3'
    glassfish_version: '5.0'
  tasks:
  - name: Create system user for ActiveMQ
    user:
      name: "{{item}}"
      system: yes
      local: yes
      createhome: yes
      home: "/opt/{{item}}"
      shell: /bin/nologin
    with_items:
      - activemq
      - glassfish

  - name: Install OpenJDK 8
    yum:
      name: 'java-1.8.0-openjdk'
      state: present

  - name: Download and unpack ActiveMQ
    unarchive:
      src: 'http://www.apache.org/dyn/closer.cgi?filename=/activemq/{{activemq_version}}/apache-activemq-{{activemq_version}}-bin.tar.gz&action=download'
      dest: /opt/activemq
      creates: '/opt/activemq/activemq-all-{{activemq_version}}.jar'
      remote_src: yes
      extra_opts: "--strip-components=1"
      owner: activemq
      group: activemq

  - name: Upload Systemd unit file for ActiveMQ
    copy:
      src: activemq.service
      dest: /usr/lib/systemd/system/activemq.service
        
  - name: Install unzip
    yum:
      name: unzip
      state: present

  - name: Download and unpack Glassfish
    unarchive:
      src: 'http://download.oracle.com/glassfish/{{glassfish_version}}/release/glassfish-{{glassfish_version}}.zip'
      dest: /opt
      creates: /opt/glassfish5
      remote_src: yes
      owner: glassfish
      group: glassfish

  - name: Move Glassfish files to HOME
    shell: mv /opt/glassfish5/* /opt/glassfish
    become_user: glassfish

  - name: Remove glassfish5 directory
    file:
      path: /opt/glassfish5
      state: absent

  - name: Upload Systemd unit file for Glassfish
    copy:
      src: glassfish.service
      dest: /usr/lib/systemd/system/glassfish.service

  - name: Download ActiveMQ RAR
    get_url:
      url: 'http://repo1.maven.org/maven2/org/apache/activemq/activemq-rar/{{activemq_version}}/activemq-rar-{{activemq_version}}.rar'
      dest: /tmp
    become: False

  - name: Start ActiveMQ and Glassfish
    service:
      name: "{{item}}"
      state: started
      enabled: yes
    with_items:
      - activemq
      - glassfish

  - name: Deploy ActiveMQ RAR
    command: '/opt/glassfish/bin/asadmin deploy --type rar --name activemq-rar /tmp/activemq-rar-{{activemq_version}}.rar'
    become_user: glassfish

  - name: Create Resource Adapter Config
    command: "/opt/glassfish/bin/asadmin create-resource-adapter-config --threadpoolid thread-pool-1 --property ServerUrl='tcp\\://localhost\\:61616':UserName='admin':Password='admin':UseInboundSession=false activemq-rar"
    become_user: glassfish

  - name: Create Connector Connection Pool
    command: '/opt/glassfish/bin/asadmin create-connector-connection-pool --raname activemq-rar --connectiondefinition javax.jms.ConnectionFactory --ping true --isconnectvalidatereq true jms/activeMqConnectionPool'
    become_user: glassfish

  - name: Create JNDI Admin Object
    command: '/opt/glassfish/bin/asadmin create-admin-object --raname activemq-rar --restype javax.jms.Queue --property PhysicalName=MQ.IN jms/queue/MQ.IN'
    become_user: glassfish

  - name: Configure firewall
    command: 'firewall-cmd --zone=public --permanent --add-port={{item}}/tcp'
    with_items:
      - 8161
      - 61616
      - 61613

  - name: Reload firewall rules
    command: firewall-cmd --reload
