---
- hosts: localhost
  user: vagrant

- hosts: all
  become: True
  become_method: sudo
  vars:
    virtualenv_dir: /opt/fludetector/venv
    listen_as: http
    fludetector_user: root
  tasks:
    - name: Install EPEL repository
      yum: name=epel-release state=present

    - name: Install Python 2.7 and Pip
      yum: name={{item}} state=present
      with_items:
        - python
        - python-pip

    - name: Install SQLite3 and lzop
      yum: name={{item}} state=latest
      with_items:
        - sqlite
        - lzop

    - name: Update pip and virtualenv
      pip: name={{item}} state=latest
      with_items:
        - pip
        - virtualenv
      
    - name: Setup a Python 2.7 environment
      shell: virtualenv -p /usr/bin/python2.7 {{virtualenv_dir}}

    - name: Create fludetector log directory
      file: path=/opt/fludetector/logs state=directory

    - name: Deploy fludetector Flask app
      unarchive: src=https://github.com/UCL/fludetector-flask/archive/v2.2.tar.gz dest=/opt/fludetector/ remote_src=yes extra_opts="--strip-components=1"

    - name: Copy env file
      copy: src=conf/env dest=/opt/fludetector/.env

    - name: Configure fludetector Flask app
      command: /opt/fludetector/scripts/init.sh chdir=/opt/fludetector

    - name: Upload seed data
      copy: src=conf/seed.sql dest=/opt/fludetector/seed.sql

    - name: Import seed data
      shell: sqlite3 data.db < seed.sql
      args:
        chdir: /opt/fludetector

    - name: Install Supervisor
      yum: name=supervisor state=present

    - name: Deploy Supervisor configuration for Flask-Gunicorn app
      template: src=conf/supervisor.ini.j2 dest=/etc/supervisord.d/fludetector.ini
      
    - name: Install Nginx
      yum: name=nginx state=present

    - name: Upload Nginx configuration for fludetector
      copy: src=conf/nginx.conf dest=/etc/nginx/conf.d/fludetector.conf

    - name: Enable nginx port in firewall
      command: firewall-cmd --zone=public --permanent --add-service={{listen_as}}

    - name: Start nginx
      systemd: name=nginx state=started enabled=yes

    - name: Start supervisord
      systemd: name=supervisord state=started enabled=yes

    - name: Restart firewalld
      systemd: name=firewalld state=restarted
