# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos-7.5"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.compatibility_mode = "2.0"
    ansible.extra_vars = {
      target: "all"
    }
  end
  
  config.vm.network "forwarded_port", guest: 80, host: 10080

end
